x-default-mongo: &default-mongo
  image: mongo:6.0.5
  restart: no
  networks:
    - mongo-network

services:
  mongos-router:
    <<: *default-mongo
    command: mongos -f /app/mongos.conf
    environment:
      MONGO_USER: "${MONGO_USER}"
      MONGO_PASSWORD: "${MONGO_PASSWORD}"
    depends_on:
      - mongo-csrs-node1
      - mongo-rs1-node1
      - mongo-rs2-node1
    networks:
      - mongo-network
      - polynotes-network
    volumes:
      - mongos-router:/data/db
      - ./mongo/router:/app

  # Mongo configurations
  ## RS0
  mongo-csrs-node1:
    <<: *default-mongo
    command: mongod -f /app/mongod.conf
    depends_on:
      - mongo-csrs-node2
      - mongo-csrs-node3
    volumes:
      - mongo-csrs-node1:/data/db
      - ./mongo/csrs:/app

  mongo-csrs-node2:
    <<: *default-mongo
    command: mongod -f /app/mongod.conf
    volumes:
      - mongo-csrs-node2:/data/db
      - ./mongo/csrs:/app

  mongo-csrs-node3:
    <<: *default-mongo
    command: mongod -f /app/mongod.conf
    volumes:
      - mongo-csrs-node3:/data/db
      - ./mongo/csrs:/app

  # Mongo sharded replica sets (2)
  ## RS1
  mongo-rs1-node1:
    <<: *default-mongo
    command: mongod -f /app/mongod.conf
    depends_on:
      - mongo-rs1-node2
      - mongo-rs1-node3
    volumes:
      - mongo-rs1-node1:/data/db
      - ./mongo/rs1:/app

  mongo-rs1-node2:
    <<: *default-mongo
    command: mongod -f /app/mongod.conf
    volumes:
      - mongo-rs1-node2:/data/db
      - ./mongo/rs1:/app

  mongo-rs1-node3:
    <<: *default-mongo
    command: mongod -f /app/mongod.conf
    volumes:
      - mongo-rs1-node3:/data/db
      - ./mongo/rs1:/app

  ## RS2
  mongo-rs2-node1:
    <<: *default-mongo
    command: mongod -f /app/mongod.conf
    depends_on:
      - mongo-rs2-node2
      - mongo-rs2-node3
    volumes:
      - mongo-rs2-node1:/data/db
      - ./mongo/rs2:/app

  mongo-rs2-node2:
    <<: *default-mongo
    command: mongod -f /app/mongod.conf
    volumes:
      - mongo-rs2-node2:/data/db
      - ./mongo/rs2:/app

  mongo-rs2-node3:
    <<: *default-mongo
    command: mongod -f /app/mongod.conf
    volumes:
      - mongo-rs2-node3:/data/db
      - ./mongo/rs2:/app

networks:
  mongo-network:
  polynotes-network:

volumes:
  mongos-router:
  mongo-csrs-node1:
  mongo-csrs-node2:
  mongo-csrs-node3:
  mongo-rs1-node1:
  mongo-rs1-node2:
  mongo-rs1-node3:
  mongo-rs2-node1:
  mongo-rs2-node2:
  mongo-rs2-node3: